export default [
  {
    "login": "sarahashimova",
    "id": 104199468,
    "node_id": "U_kgDOBjX1LA",
    "avatar_url": "https://avatars.githubusercontent.com/u/104199468?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sarahashimova",
    "html_url": "https://github.com/sarahashimova",
    "followers_url": "https://api.github.com/users/sarahashimova/followers",
    "following_url": "https://api.github.com/users/sarahashimova/following{/other_user}",
    "gists_url": "https://api.github.com/users/sarahashimova/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sarahashimova/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sarahashimova/subscriptions",
    "organizations_url": "https://api.github.com/users/sarahashimova/orgs",
    "repos_url": "https://api.github.com/users/sarahashimova/repos",
    "events_url": "https://api.github.com/users/sarahashimova/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sarahashimova/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "frakovski",
    "id": 106008018,
    "node_id": "U_kgDOBlGN0g",
    "avatar_url": "https://avatars.githubusercontent.com/u/106008018?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/frakovski",
    "html_url": "https://github.com/frakovski",
    "followers_url": "https://api.github.com/users/frakovski/followers",
    "following_url": "https://api.github.com/users/frakovski/following{/other_user}",
    "gists_url": "https://api.github.com/users/frakovski/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/frakovski/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/frakovski/subscriptions",
    "organizations_url": "https://api.github.com/users/frakovski/orgs",
    "repos_url": "https://api.github.com/users/frakovski/repos",
    "events_url": "https://api.github.com/users/frakovski/events{/privacy}",
    "received_events_url": "https://api.github.com/users/frakovski/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "IsrafilliRamin",
    "id": 106513116,
    "node_id": "U_kgDOBllC3A",
    "avatar_url": "https://avatars.githubusercontent.com/u/106513116?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/IsrafilliRamin",
    "html_url": "https://github.com/IsrafilliRamin",
    "followers_url": "https://api.github.com/users/IsrafilliRamin/followers",
    "following_url": "https://api.github.com/users/IsrafilliRamin/following{/other_user}",
    "gists_url": "https://api.github.com/users/IsrafilliRamin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/IsrafilliRamin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/IsrafilliRamin/subscriptions",
    "organizations_url": "https://api.github.com/users/IsrafilliRamin/orgs",
    "repos_url": "https://api.github.com/users/IsrafilliRamin/repos",
    "events_url": "https://api.github.com/users/IsrafilliRamin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/IsrafilliRamin/received_events",
    "type": "User",
    "site_admin": false
  }
]