export default {
  login: "alasgar88",
  id: 85016138,
  node_id: "MDQ6VXNlcjg1MDE2MTM4",
  avatar_url: "https://avatars.githubusercontent.com/u/85016138?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/alasgar88",
  html_url: "https://github.com/alasgar88",
  followers_url: "https://api.github.com/users/alasgar88/followers",
  following_url:
    "https://api.github.com/users/alasgar88/following{/other_user}",
  gists_url: "https://api.github.com/users/alasgar88/gists{/gist_id}",
  starred_url: "https://api.github.com/users/alasgar88/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/alasgar88/subscriptions",
  organizations_url: "https://api.github.com/users/alasgar88/orgs",
  repos_url: "https://api.github.com/users/alasgar88/repos",
  events_url: "https://api.github.com/users/alasgar88/events{/privacy}",
  received_events_url: "https://api.github.com/users/alasgar88/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 3,
  following: 1,
  created_at: "2021-05-29T09:53:35Z",
  updated_at: "2022-09-19T12:41:09Z",
};
